name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t django-app .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 -e DJANGO_SECRET_KEY="dev-secret-key" --name test-app django-app

      - name: Check running containers
        run: docker ps -a

      - name: Wait for app
        run: sleep 10

      - name: Test with curl
        run: curl -f http://localhost:8000

    sbom-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SBOM scan (custom action)
        uses: ./.github/actions/sbom-scan
